#!/bin/bash
########
##################################
VERDE=`echo -e "\e[32m"`
NORMAL=`echo -e "\e[0m"`
AZUL=`echo -e "\e[34m"`
ROJO=`echo -e "\e[31m"`
ULTRAVERDE=`echo -e "\e[1;32m"`
AMARILLO=`echo -e "\e[1;33m"`
VIOLETA=`echo -e "\e[1;35m"`
#################################
trap 'tput cnorm;echo; exit 0' INT
function banner () {
echo
echo "${AMARILLO} ___  __  ____  _  _  _  _  ___  __   "
echo "(  ,\(  )(_  _)( )( )( \( )(  _)(  )  "
echo " ) _/ )(   )(   )()(  )  (  ) _) )(__  LISTENER"
echo "(_)  (__) (__)  \__/ (_)\_)(___)(____)${NORMAL} by chewwe"
echo
}
function force () {
echo " Tardara un minuto en volver a tratar de reconectar la shell. Si una vez puesta en marcha la cuenta atras, pasara mas de un minuto, habras perdido la shell para siempre."
service ssh stop && sleep 60 && service ssh start
tunel
}
function limpieza () {
for pid in $(netstat -patl | grep 21270 | awk '{print $7}' | awk -F "/" '{print $1}' | head -1  ); do 
kill $pid 2>/dev/null
done
}
function tunel()	{
ssh  -X  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 21270 root@localhost  
clear
banner
tput civis
echo -ne "${AZUL}[${NORMAL}||${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}10${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}//${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}9 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}--${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}8 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}\\\\\\${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}7 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}||${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}6 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}//${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}5 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}--${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}4 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}\\\\\\${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}3 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}||${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}2 ${NORMAL}\r";sleep 1;
echo -ne "${AZUL}[${NORMAL}--${AZUL}]${NORMAL} Reintentando conexion en ${AMARILLO}1 ${NORMAL}\r";sleep 1;
tput cnorm
tunel
}
if [ "$1" = force ];then
force
elif [ "$1" = clean ];then
limpieza
else
tunel
fi
tunel
